# Generated by Django 4.2.2 on 2023-12-12 20:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
