# Generated by Django 4.2.2 on 2024-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0003_projets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projets",
            old_name="lin",
            new_name="lien",
        ),
        migrations.AlterField(
            model_name="projets",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
