# Generated by Django 4.2.2 on 2024-08-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0004_rename_lin_projets_lien_alter_projets_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("image", models.ImageField(upload_to="")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
