# Generated by Django 4.2.2 on 2024-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0005_entreprise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricings",
            name="image",
        ),
        migrations.AddField(
            model_name="pricings",
            name="icon_class",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
