# Generated by Django 4.2.2 on 2024-08-27 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0006_remove_pricings_image_pricings_icon_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogs",
            options={"ordering": ["date"]},
        ),
    ]
