# Generated by Django 4.2.2 on 2024-08-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0007_alter_blogs_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.TextField(),
        ),
    ]
