# Generated by Django 4.2.2 on 2024-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0008_alter_blogs_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="customer",
        ),
        migrations.AddField(
            model_name="reviews",
            name="image",
            field=models.ImageField(default=2, upload_to=""),
            preserve_default=False,
        ),
    ]
