# Generated by Django 4.2.2 on 2024-10-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0009_remove_reviews_customer_reviews_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="nom",
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
