# Generated by Django 4.2.2 on 2024-10-23 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0012_alter_blogs_description_alter_services_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="description",
            new_name="content",
        ),
    ]
